language: python

dist: xenial
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"

install:
  - pip install -e .
  - pip install pytest-cov
  - pip install codecov

script:
  - python setup.py test
  - py.test --cov=CYLGame
  - pip install sphinx; cd docs; make html; touch _build/html/.nojekyll; cd ..

after_success:
  - codecov

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  keep-history: true
  allow_empty_commit: false
  on:
    branch: master
  local_dir: docs/_build/html/
